add new community fHACKtory
lyontechhub/lyontechhub.github.io pull request #82
Opened 2017-04-22 20:24 UTC by cbelhaffef

Please add the community [fHackTory](http://www.fHACKtory.com)

2017-04-22 20:31 UTC, thebignet commented
J'ai l'impression qu'il manque le fichier json dans le répertoire communities. Regarde le README, il y a des exemples.

2017-05-22 07:35 UTC, clacote requested changes
Deux typos.

2017-05-22 07:35 UTC, clacote commented on data/communities.json
> +        "shortDescription": "Organisateur d'un hackathon indépendant sur Lyon, 100% Hack, 0% bullshit, on réunit des passionés du developpement logiciel, d'électronique, de makers, de designers et de
passionés -> passionnés

2017-05-22 07:35 UTC, clacote commented on data/communities.json
> +        "shortDescription": "Organisateur d'un hackathon indépendant sur Lyon, 100% Hack, 0% bullshit, on réunit des passionés du developpement logiciel, d'électronique, de makers, de designers et de
developpement -> développement

2017-09-22 04:47 UTC, jeantil commented
hello @cbelhaffef, 
il manque effectivement un fichier fhacktory.json dans le dossier data. 

si tu mets à jour tout ça et que tu rebase la branche sur master, on se fera un plaisir de vous ajouter.

2020-03-09 15:42 UTC, fnicollet commented
Cette ancienne PR n'est plus d'actualité et peut être fermée. 
 Voici la PR complète pour ajouter fHACKtory:
https://github.com/lyontechhub/lyontechhub.github.io/pull/105

2020-03-09 15:47 UTC, closed without merging